export const SET_PDFJS_LIB = 'SET_PDFJS_LIB';
export const SET_FILE = 'SET_FILE';
export const SET_FILE_STATUS = 'SET_FILE_STATUS';
export const SET_PDF = 'SET_PDF';
export const SET_PAGE_PROMISES = 'SET_PAGE_PROMISES';
export const SET_RESOLVED_PAGE = 'SET_RESOLVED_PAGE';
export const SET_SLIDE_NUMBER = 'SET_SLIDE_NUMBER';
export const SET_CONTAINER_HEIGHT = 'SET_CONTAINER_HEIGHT';